### PR TITLE
update all modules

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the conventions in the [contribution docs](https://github.com/nf-wrap/main/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run tools/<TOOL>/. -profile laptop,docker --test --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]
this seems like very few modules. Does this repo have a changelog?

**Comment by maxulysse** [comment]
No, I'll add that, and some tests should be triggered as well :facepalm:

**Comment by maxulysse** [comment]
Will fix #23 
But need to fix a couple of more things at the same time.
Using nf-validation, and do some proper refactoring

**Comment by maxulysse** [comment]
Need to do some more cleanup and add more tests, but I'd rather merge that one ASAP, that way we fix #23 in dev

**Pull request merged**
